---
- hosts: cisco_routers
  gather_facts: true
  connection: local

  tasks: 

   - name: Define Connection
     set_fact:
       connection:
         authorize: yes
         username: "{{provider.username}}"
         password: "{{provider.password}}"
         host: "{{inventory_hostname}}"
    
   - name: Configure OSFP 100 and put all interfaces into OSPF Area 0
     ios_config:
       provider: "{{connection}}"
       lines:
       - network 10.0.0.0 0.255.255.255 area 0
       parents: router ospf 100

   - name: SAVE CONFIG 
     ios_command:
       provider: "{{connection}}"
       commands:
         - write memory

   - name: Verify OSPF interface is Active
     ios_command:
       provider: "{{connection}}"
       commands: 
         - sh run | sec router ospf 
       waitfor:
         - result[0] contains 'router ospf 100'
